
let data = [
 
    {
    'BilliansID':51  ,
    'Name': 'Facility51',
    'Location': 'Dallas',
    'State': 'Chicago',
    'PAS': 'Meditech',
    'FacilityID': 51,
    'Export Start': 2200,
    'Finish Export': 2300,
    'Export_Status': 'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 2000,
    'Script_Finish':2400,
    'RecordCount':  5,
    'SuccessCount': 6,
    'FailureCount': 7,
    'Records_From_Prev_Day': 45,
    'Ignores':  34,
    'Server':    250,
    'COID':     510,
    'ServiceCode_Count': 45,
    'Record_Count':  67,
    'Error_Details':  78,
    'Ignore_ServiceCode_List':  12,
    'Supercedes_Record_Count':  6,
    'SuperCedes_Service_Code_List': 2
   
    
    },
   
  
    
    
    
    {
    'BilliansID': 53,
    'Name': 'Facility53',
    'Location': 'Washington',
    'State': 'New York',
    'PAS': 'Paragon',
    'FacilityID': 53,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 'Failed',
    'Script_Status': 'Failed',
    'Script_Start': 2100,
    'Script_Finish': 2105,
    'RecordCount':  12,
    'SuccessCount': 234,
    'FailureCount':  23,
    'Records_From_Prev_Day': 26,
    'Ignores': 10,
    'Server': 254,
    'COID': 530,
    'ServiceCode_Count': 45,
    'Record_Count': 78,
    'Error_Details':  87,
    'Ignore_ServiceCode_List': 21,
    'Supercedes_Record_Count': 76,
    'SuperCedes_Service_Code_List':21
   
    
    },
   
    {
    'BilliansID': 54,
    'Name': 'Facility54',
    'Location': 'Michigan',
    'State':  'New York',
    'PAS': 'Cerner',
    'FacilityID': 54,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 2100,
    'Script_Status': 'Passed',
    'Script_Start':  1200,
    'Script_Finish': 2300,
    'RecordCount': 11,
    'SuccessCount': 12,
    'FailureCount': 14,
    'Records_From_Prev_Day': 230,
    'Ignores': 12,
    'Server': 255,
    'COID': 54,
    'ServiceCode_Count': 230,
    'Record_Count':  23,
    'Error_Details':   11,
    'Ignore_ServiceCode_List': 45 ,
    'Supercedes_Record_Count':  67,
    'SuperCedes_Service_Code_List':78
    },
    {
    'BilliansID':55  ,
    'Name': 'Facility55',
    'Location': 'Dallas',
    'State': 'Chicago',
    'PAS': 'Meditech',
    'FacilityID': 55,
    'Export Start': 2200,
    'Finish Export': 2300,
    'Export_Status': 'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 2000,
    'Script_Finish':2400,
    'RecordCount':  5,
    'SuccessCount': 6,
    'FailureCount': 7,
    'Records_From_Prev_Day': 45,
    'Ignores':  34,
    'Server':    250,
    'COID':     550,
    'ServiceCode_Count': 45,
    'Record_Count':  67,
    'Error_Details':  78,
    'Ignore_ServiceCode_List':  12,
    'Supercedes_Record_Count':  6,
    'SuperCedes_Service_Code_List': 2
   
    
    },
   
    {
    'BilliansID':56,
    'Name': 'Facility56'  ,
    'Location': 'Denver',
    'State':  'illinois',
    'PAS':  'Cerner',
    'FacilityID':  56,
    'Export Start': 2300,
    'Finish Export': 2330,
    'Export_Status':  'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 567,
    'Script_Finish': 100,
    'RecordCount':  34,
    'SuccessCount': 45,
    'FailureCount':  3,
    'Records_From_Prev_Day': 12,
    'Ignores':  10,
    'Server':   251,
    'COID':  560,
    'ServiceCode_Count': 13,
    'Record_Count':  12,
    'Error_Details': 45,
    'Ignore_ServiceCode_List': 19,
    'Supercedes_Record_Count': 34,
    'SuperCedes_Service_Code_List': 21
   
    
    },
   
    
    
    {
    'BilliansID': 57,
    'Name': 'Facility57',
    'Location': 'Washington',
    'State': 'New York',
    'PAS': 'Paragon',
    'FacilityID': 57,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 'Failed',
    'Script_Status': 'Failed',
    'Script_Start': 2100,
    'Script_Finish': 2105,
    'RecordCount':  12,
    'SuccessCount': 234,
    'FailureCount':  23,
    'Records_From_Prev_Day': 26,
    'Ignores': 10,
    'Server': 254,
    'COID': 570,
    'ServiceCode_Count': 45,
    'Record_Count': 78,
    'Error_Details':  87,
    'Ignore_ServiceCode_List': 21,
    'Supercedes_Record_Count': 76,
    'SuperCedes_Service_Code_List':21
   
    
    },
   
    {
    'BilliansID': 58,
    'Name': 'Facility58',
    'Location': 'Michigan',
    'State':  'New York',
    'PAS': 'Cerner',
    'FacilityID': 54,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 2100,
    'Script_Status': 'Passed',
    'Script_Start':  1200,
    'Script_Finish': 2300,
    'RecordCount': 11,
    'SuccessCount': 12,
    'FailureCount': 14,
    'Records_From_Prev_Day': 230,
    'Ignores': 12,
    'Server': 255,
    'COID': 58,
    'ServiceCode_Count': 230,
    'Record_Count':  23,
    'Error_Details':   11,
    'Ignore_ServiceCode_List': 45 ,
    'Supercedes_Record_Count':  67,
    'SuperCedes_Service_Code_List':78
    },
    {
    'BilliansID':59  ,
    'Name': 'Facility59',
    'Location': 'Dallas',
    'State': 'Chicago',
    'PAS': 'Meditech',
    'FacilityID': 59,
    'Export Start': 2200,
    'Finish Export': 2300,
    'Export_Status': 'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 2000,
    'Script_Finish':2400,
    'RecordCount':  5,
    'SuccessCount': 6,
    'FailureCount': 7,
    'Records_From_Prev_Day': 45,
    'Ignores':  34,
    'Server':    250,
    'COID':     590,
    'ServiceCode_Count': 45,
    'Record_Count':  67,
    'Error_Details':  78,
    'Ignore_ServiceCode_List':  12,
    'Supercedes_Record_Count':  6,
    'SuperCedes_Service_Code_List': 2
   
    
    },
   
    {
    'BilliansID':60,
    'Name': 'Facility60'  ,
    'Location': 'Denver',
    'State':  'illinois',
    'PAS':  'Cerner',
    'FacilityID':  60,
    'Export Start': 2300,
    'Finish Export': 2330,
    'Export_Status':  'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 567,
    'Script_Finish': 100,
    'RecordCount':  34,
    'SuccessCount': 45,
    'FailureCount':  3,
    'Records_From_Prev_Day': 12,
    'Ignores':  10,
    'Server':   251,
    'COID':  600,
    'ServiceCode_Count': 13,
    'Record_Count':  12,
    'Error_Details': 45,
    'Ignore_ServiceCode_List': 19,
    'Supercedes_Record_Count': 34,
    'SuperCedes_Service_Code_List': 21
   
    
    },
   
    
    
    {
    'BilliansID': 61,
    'Name': 'Facility61',
    'Location': 'Washington',
    'State': 'New York',
    'PAS': 'Paragon',
    'FacilityID': 61,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 'Failed',
    'Script_Status': 'Failed',
    'Script_Start': 2100,
    'Script_Finish': 2105,
    'RecordCount':  12,
    'SuccessCount': 234,
    'FailureCount':  23,
    'Records_From_Prev_Day': 26,
    'Ignores': 10,
    'Server': 254,
    'COID': 610,
    'ServiceCode_Count': 45,
    'Record_Count': 78,
    'Error_Details':  87,
    'Ignore_ServiceCode_List': 21,
    'Supercedes_Record_Count': 76,
    'SuperCedes_Service_Code_List':21
   
    
    },
   
    {
    'BilliansID': 62,
    'Name': 'Facility62',
    'Location': 'Michigan',
    'State':  'New York',
    'PAS': 'Cerner',
    'FacilityID': 62,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 2100,
    'Script_Status': 'Passed',
    'Script_Start':  1200,
    'Script_Finish': 2300,
    'RecordCount': 11,
    'SuccessCount': 12,
    'FailureCount': 14,
    'Records_From_Prev_Day': 230,
    'Ignores': 12,
    'Server': 255,
    'COID': 62,
    'ServiceCode_Count': 230,
    'Record_Count':  23,
    'Error_Details':   11,
    'Ignore_ServiceCode_List': 45 ,
    'Supercedes_Record_Count':  67,
    'SuperCedes_Service_Code_List':78
    },
    {
    'BilliansID':63  ,
    'Name': 'Facility63',
    'Location': 'Dallas',
    'State': 'Chicago',
    'PAS': 'Meditech',
    'FacilityID': 63,
    'Export Start': 2200,
    'Finish Export': 2300,
    'Export_Status': 'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 2000,
    'Script_Finish':2400,
    'RecordCount':  5,
    'SuccessCount': 6,
    'FailureCount': 7,
    'Records_From_Prev_Day': 45,
    'Ignores':  34,
    'Server':    250,
    'COID':     630,
    'ServiceCode_Count': 45,
    'Record_Count':  67,
    'Error_Details':  78,
    'Ignore_ServiceCode_List':  12,
    'Supercedes_Record_Count':  6,
    'SuperCedes_Service_Code_List': 2
   
    
    },
   
    {
    'BilliansID':64,
    'Name': 'Facility64'  ,
    'Location': 'Denver',
    'State':  'illinois',
    'PAS':  'Cerner',
    'FacilityID':  64,
    'Export Start': 2300,
    'Finish Export': 2330,
    'Export_Status':  'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 567,
    'Script_Finish': 100,
    'RecordCount':  34,
    'SuccessCount': 45,
    'FailureCount':  3,
    'Records_From_Prev_Day': 12,
    'Ignores':  10,
    'Server':   251,
    'COID':  640,
    'ServiceCode_Count': 13,
    'Record_Count':  12,
    'Error_Details': 45,
    'Ignore_ServiceCode_List': 19,
    'Supercedes_Record_Count': 34,
    'SuperCedes_Service_Code_List': 21
   
    
    },
   
    
    
    {
    'BilliansID': 65,
    'Name': 'Facility65',
    'Location': 'Washington',
    'State': 'New York',
    'PAS': 'Paragon',
    'FacilityID': 65,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 'Failed',
    'Script_Status': 'Failed',
    'Script_Start': 2100,
    'Script_Finish': 2105,
    'RecordCount':  12,
    'SuccessCount': 234,
    'FailureCount':  23,
    'Records_From_Prev_Day': 26,
    'Ignores': 10,
    'Server': 254,
    'COID': 650,
    'ServiceCode_Count': 45,
    'Record_Count': 78,
    'Error_Details':  87,
    'Ignore_ServiceCode_List': 21,
    'Supercedes_Record_Count': 76,
    'SuperCedes_Service_Code_List':21
   
    
    },
   
    {
    'BilliansID': 66,
    'Name': 'Facility66',
    'Location': 'Michigan',
    'State':  'New York',
    'PAS': 'Cerner',
    'FacilityID': 66,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 2100,
    'Script_Status': 'Passed',
    'Script_Start':  1200,
    'Script_Finish': 2300,
    'RecordCount': 11,
    'SuccessCount': 12,
    'FailureCount': 14,
    'Records_From_Prev_Day': 230,
    'Ignores': 12,
    'Server': 255,
    'COID': 66,
    'ServiceCode_Count': 230,
    'Record_Count':  23,
    'Error_Details':   11,
    'Ignore_ServiceCode_List': 45 ,
    'Supercedes_Record_Count':  67,
    'SuperCedes_Service_Code_List':78
    },
    {
    'BilliansID':67  ,
    'Name': 'Facility67',
    'Location': 'Dallas',
    'State': 'Chicago',
    'PAS': 'Meditech',
    'FacilityID': 67,
    'Export Start': 2200,
    'Finish Export': 2300,
    'Export_Status': 'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 2000,
    'Script_Finish':2400,
    'RecordCount':  5,
    'SuccessCount': 6,
    'FailureCount': 7,
    'Records_From_Prev_Day': 45,
    'Ignores':  34,
    'Server':    250,
    'COID':     670,
    'ServiceCode_Count': 45,
    'Record_Count':  67,
    'Error_Details':  78,
    'Ignore_ServiceCode_List':  12,
    'Supercedes_Record_Count':  6,
    'SuperCedes_Service_Code_List': 2
   
    
    },
   
    {
    'BilliansID':68,
    'Name': 'Facility68'  ,
    'Location': 'Denver',
    'State':  'illinois',
    'PAS':  'Cerner',
    'FacilityID':  68,
    'Export Start': 2300,
    'Finish Export': 2330,
    'Export_Status':  'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 234,
    'Script_Finish': 343,
    'RecordCount':  34,
    'SuccessCount': 45,
    'FailureCount':  3,
    'Records_From_Prev_Day': 12,
    'Ignores':  10,
    'Server':   251,
    'COID':  680,
    'ServiceCode_Count': 13,
    'Record_Count':  12,
    'Error_Details': 45,
    'Ignore_ServiceCode_List': 19,
    'Supercedes_Record_Count': 34,
    'SuperCedes_Service_Code_List': 21
   
    
    },
   
    
    
    {
    'BilliansID': 69,
    'Name': 'Facility69',
    'Location': 'Washington',
    'State': 'New York',
    'PAS': 'Paragon',
    'FacilityID': 69,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 'Failed',
    'Script_Status': 'Failed',
    'Script_Start': 2100,
    'Script_Finish': 2105,
    'RecordCount':  12,
    'SuccessCount': 234,
    'FailureCount':  23,
    'Records_From_Prev_Day': 26,
    'Ignores': 10,
    'Server': 254,
    'COID': 690,
    'ServiceCode_Count': 45,
    'Record_Count': 78,
    'Error_Details':  87,
    'Ignore_ServiceCode_List': 21,
    'Supercedes_Record_Count': 76,
    'SuperCedes_Service_Code_List':21
   
    
    },
   
   
    
    {
    'BilliansID':76,
    'Name': 'Facility76'  ,
    'Location': 'Denver',
    'State':  'illinois',
    'PAS':  'Cerner',
    'FacilityID':  76,
    'Export Start': 2300,
    'Finish Export': 2330,
    'Export_Status':  'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 10,
    'Script_Finish': 100,
    'RecordCount':  34,
    'SuccessCount': 45,
    'FailureCount':  3,
    'Records_From_Prev_Day': 12,
    'Ignores':  10,
    'Server':   251,
    'COID':  760,
    'ServiceCode_Count': 13,
    'Record_Count':  12,
    'Error_Details': 45,
    'Ignore_ServiceCode_List': 19,
    'Supercedes_Record_Count': 34,
    'SuperCedes_Service_Code_List': 21
   
    
    },
   
    
    
    {
    'BilliansID': 77,
    'Name': 'Facility77',
    'Location': 'Washington',
    'State': 'New York',
    'PAS': 'Paragon',
   'FacilityID': 77,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 'Failed',
    'Script_Status': 'Failed',
    'Script_Start': 2100,
    'Script_Finish': 2105,
    'RecordCount':  12,
    'SuccessCount': 234,
    'FailureCount':  23,
    'Records_From_Prev_Day': 26,
    'Ignores': 10,
    'Server': 254,
    'COID': 770,
    'ServiceCode_Count': 45,
    'Record_Count': 78,
    'Error_Details':  87,
    'Ignore_ServiceCode_List': 21,
    'Supercedes_Record_Count': 76,
    'SuperCedes_Service_Code_List':21
   
    
    },
   
    {
    'BilliansID': 78,
    'Name': 'Facility78',
    'Location': 'Michigan',
    'State':  'New York',
    'PAS': 'Cerner',
    'FacilityID': 78,
    'Export Start': 2100,
    'Finish Export': 2300,
    'Export_Status': 2100,
    'Script_Status': 'Passed',
    'Script_Start':  1200,
    'Script_Finish': 2300,
    'RecordCount': 11,
    'SuccessCount': 12,
    'FailureCount': 14,
    'Records_From_Prev_Day': 230,
    'Ignores': 12,
    'Server': 255,
    'COID': 78,
    'ServiceCode_Count': 230,
    'Record_Count':  23,
    'Error_Details':   11,
    'Ignore_ServiceCode_List': 45 ,
    'Supercedes_Record_Count':  67,
    'SuperCedes_Service_Code_List':78
    },
    {
    'BilliansID':79  ,
    'Name': 'Facility79',
    'Location': 'Dallas',
    'State': 'Chicago',
    'PAS': 'Meditech',
    'FacilityID': 79,
    'Export Start': 2200,
    'Finish Export': 2300,
    'Export_Status': 'Passed',
    'Script_Status': 'Passed',
    'Script_Start': 2000,
    'Script_Finish':2400,
    'RecordCount':  5,
    'SuccessCount': 6,
    'FailureCount': 7,
    'Records_From_Prev_Day': 45,
    'Ignores':  34,
    'Server':    250,
    'COID':     790,
    'ServiceCode_Count': 45,
    'Record_Count':  67,
    'Error_Details':  78,
    'Ignore_ServiceCode_List':  12,
    'Supercedes_Record_Count':  6,
    'SuperCedes_Service_Code_List': 2
     },
     {
      'BilliansID' : 1,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 1,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 10,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 2,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 2,
      'Export Start' : '2018-09-18',
      'Finish export' : '2018-09-18',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18' ,
      'Script_Finish' : '2018-09-18',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
     'Server' : 258,
      'COID' : 20,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 3,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 3,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '030',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 4,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'MeditechHCA',
      'FacilityId' : 4,
      'Export Start' : '2018-09-18',
      'Finish export' : '2018-09-18',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18',
      'Script_Finish' : '2018-09-18',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 40,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 5,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 5,
      'Export Start' : '2018-09-18',
      'Finish export' : '2018-09-18190201620-0500',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18',
      'Script_Finish' : 'dfdf',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 50,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 6,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 6,
      'Export Start' : '2018-09-18190019.6600500',
      'Finish export' : '2018-09-181901169770500',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18',
      'Script_Finish' : '2018-09-18',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 60,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 7,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 7,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '070',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
 
  
      {
      'BilliansID' : 10,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 10,
      'Export Start' : '2018-09-18',
      'Finish export' : '2018-09-18',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 100,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 11,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 11,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0110',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 12,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 12,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
     'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 120,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 13,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 13,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 130,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 14,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 14,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 140,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
     'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 15,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 15,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0150',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 16,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 16,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 160,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 17,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 17,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 170,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 18,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 18,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 180,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 19,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 19,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0190',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 20,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 20,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' :'2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 200,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 21,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 21,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 210,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 22,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 22,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 220,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 23,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 23,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
     'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0230',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 24,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 24,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 240,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 25,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 25,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 250,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 26,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 26,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 260,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 27,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 27,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 270,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 28,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 28,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0280',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 29,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 29,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 290,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 30,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 30,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 300,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 31,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 31,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 310,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
     'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 32,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 32,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0320',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 33,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 33,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 330,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 34,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 34,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 340,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 35,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 35,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 350,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 36,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 36,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0360',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 37,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 37,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 370,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
     'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 38,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 38,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 380,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 39,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 39,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 390,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
     'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 40,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 0o40,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0400',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 41,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 0o41,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 0o410,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 42,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 0o42,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 420,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 43,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 43,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 430,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 44,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 44,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0440',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 45,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 45,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 450,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 46,
      'Name' : 'Andalusia Regional Hospital',
      'Location' : 'Andalusia',
      'State' : 'AL',
      'PAS' : 'MedHost',
      'FacilityId' : 46,
      'Export Start' : '2018-09-18 19:01:51.477 -05:00',
      'Finish export' : '2018-09-18 19:02:01.620 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 1,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 256,
      'COID' : 460,
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 47,
      'Name' : 'Vaughan Regional Medical Center Parkway Campus',
      'Location' : 'Selma',
      'State' : 'AL',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 47,
      'Export Start' : '2018-09-18 19:00:19.660 -05:00',
      'Finish export' : '2018-09-18 19:01:16.977 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 5,
      'Script_Start' : '2018-09-18 20:00:19.230 -05:00',
      'Script_Finish' : '2018-09-18 20:06:52.430 -05:00',
      'RecordCount' : 6,
      'SuccessCount' : 6,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 258,
      'COID' : 470,
      'ServiceCode_Count' : 3,
      'Record_Count' : 6,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
     'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 48,
      'Name' : 'Clark Memorial Hospital',
      'Location' : 'Jeffersonville',
      'State' : 'IN',
      'PAS' : 'Allscripts Sunrise',
      'FacilityId' : 48,
      'Export Start' : '',
      'Finish export' : '',
      'Export_Status' : 'Failure',
      'Script_Status' : 0,
      'Script_Start' : '',
      'Script_Finish' : '',
      'RecordCount' : '',
      'SuccessCount' : '',
      'FailureCount' : '',
      'Records_From_Prev_Day' : '',
      'Ignores' : '',
      'Server' : 'Unknown',
      'COID' : '0480',
      'ServiceCode_Count' : '',
      'Record_Count' : '',
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 49,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 49,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 490,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      },
      {
      'BilliansID' : 50,
      'Name' : 'Western Plains Medical Hospital',
      'Location' : 'Dodge City',
      'State' : 'KS',
      'PAS' : 'Meditech HCA',
      'FacilityId' : 50,
      'Export Start' : '2018-09-18 19:01:24.420 -05:00',
      'Finish export' : '2018-09-18 19:02:01.130 -05:00',
      'Export_Status' : 'Success',
      'Script_Status' : 2,
      'Script_Start' : '2018-09-18 20:08:25.893 -05:00',
      'Script_Finish' : '2018-09-18 20:10:57.407 -05:00',
      'RecordCount' : 2,
      'SuccessCount' : 2,
      'FailureCount' : 0,
      'Records_From_Prev_Day' : 1,
      'Ignores' : '',
      'Server' : 257,
      'COID' : 500,
      'ServiceCode_Count' : 1,
      'Record_Count' : 1,
      'Error_Details' : '',
      'Ignore_ServiceCode_List' : '',
      'Supercedes_Record_Count' : '',
      'Supercedes_Service_Code_List' : '',
      }]




serversArray= [];
pasArray = [];
facilitiesArray = [];


function getServersArray(array){
      data.forEach(function(element){
            if(!array.includes(element.Server)){
                  array.push(element.Server)
            }
            return array;
      })
}


function getPasArray(array){
      data.forEach(function(element){
            if(!array.includes(element.PAS)){
                  array.push(element.PAS)
            }
            return array;
      })
}

// function getHowManyFacilitiesInEachServer(newArray, data ){
//       let counter = 0
//       serversArray.forEach(function(server){
//             data.forEach(function(element){
//                   if(  element.Server === server){
//                         counter++
//                   }
//             })
//             newArray.push(counter)
//             counter = 0
          
            

//       })
//       console.log(newArray) ;
// }


// function reducePractice(){
//       const numbers = [1,2,3,4,5,6,7,8,9,10];

//     const sum =  numbers.reduce(function(acc, currentValue){
//             console.log(acc, currentValue)
//             return acc + currentValue
//       }, 0)
//       console.log(sum)
// }



// reducePractice()


// function forEachPractice(){
//  let numbers = [1,2,3,4,5,6,7,8,9,10];

//  numbers.forEach(function(element, index, test, test2){
//        console.log(element, index, test)
//  })

// }
// let numbers = [1,2,3,4,5,6,7,8,9,10];


function mapPractice(){
      let numbers = [1,2,3,4,5,6,7,8,9,10];

    return  numbers.map(function(item, test, test2){
          console.log( test, test2)
          if(test[item] > 5){
                console.log(test[item])
              return  item * 2

          }else{
                return  test + "estoy mayor" + item
          }
                

          
      })

      
}


// forEachPractice()
mapPractice()

console.log( mapPractice())

